inherit: 
    - models/standard.yaml
    - wandb.yaml

model:
    n_dims: 10
    n_positions: 101

training:
    data: gaussian
    task_kwargs: {}
    batch_size: 64
    learning_rate: 0.0001
    save_every_steps: 100
    keep_every_steps: 10000
    train_steps: 100000
    curriculum:
        dims:
            start: 5
            end: 10
            inc: 1
            interval: 250

wandb:
    entity: "cs182-final-project"
    project: "Sinusoidal-ICL"
